In [97]:
import pandas as pd
import numpy as np
import re
from sklearn.preprocessing import LabelEncoder

In [98]:
train = pd.read_csv('train.csv')
bc = pd.DataFrame()
bc = train[['Breed', 'Color']]
bc['Mix'] = 'Pure'
breeds = bc["Breed"].apply(lambda x: x.split(" Mix")[0])
breeds = breeds.apply(lambda x: re.sub('Black\s?|Tan\s?', '', x))
breeds = breeds.apply(lambda x: re.sub('^/', '', x))
breeds = breeds.str.replace("//", "")
breeds = breeds.apply(lambda x: pd.Series(x.split("/")))
breeds.columns = ['Breed', 'SecondaryBreed']
breed_counts = breeds["Breed"].value_counts()
frequent_breeds = breed_counts[breed_counts > 50].to_dict().keys()
breeds[~breeds['Breed'].isin(frequent_breeds)] = "Rare"

bc.drop('Breed', inplace=True, axis = 1)
bc = pd.concat([bc, breeds], axis = 1)
bc.drop('SecondaryBreed', inplace=True,axis = 1)

bc.loc[train.Breed.str.contains('Mix'),'Mix'] = 'Mix'
bc.loc[train.Breed.str.contains('/'),'Mix'] = 'Mix'

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [99]:
bc['Color'] = [x[0] for x in bc['Color'].str.split('/').tolist()]

In [100]:
b_encoder = LabelEncoder()
c_encoder = LabelEncoder()
b_encoder = b_encoder.fit(bc.Breed)
c_encoder = c_encoder.fit(bc.Color)
bc.Breed = b_encoder.transform(bc.Breed)
bc.Color = c_encoder.transform(bc.Color)

In [72]:
bc.drop('Mix', inplace = True,axis = 1)

       Color  Breed
0         15     46
1         26     27
2          7     40
3          8     27
4         49     33
5          2     14
6         12     27
7         18     27
8         40      1
9         54     14
10         2     27
11        46     38
12        15     40
13         2     54
14        54     30
15        37     27
16        18     27
17        15     40
18        54     46
19         2     46
20         2     45
21        54     27
22        16     41
23        15     28
24         2     28
25        37     27
26        23      2
27        54     18
28        26     27
29         7     46
...      ...    ...
26699     54      1
26700     49     30
26701     54     31
26702     35     50
26703     45     25
26704     54     27
26705     51     27
26706      2     27
26707     18     27
26708     54     18
26709     44     18
26710     15     18
26711     20     20
26712     23     47
26713     51     25
26714     37     27
26715      2     42
26716     54     46
26717      2     46
26718      2     51
26719     18     27
26720     18     27
26721      2     27
26722     37     27
26723      7     53
26724     18     27
26725     18     27
26726     54     46
26727      2     27
26728     18     27

[26729 rows x 2 columns]

In [81]:
cleaned_train = pd.read_csv('cleaned_train.csv')
cleaned_train = pd.concat([cleaned_train,bc], axis = 1)

In [82]:
cleaned_train.drop(['ColorCode','BreedCode'],inplace = True, axis = 1)
cleaned_train.to_csv('clean_train.csv')

In [29]:
bc.Breed = bc.Breed.apply(lambda x: x.split(' Mix')[0])
bc.Breed = bc.Breed.apply(lambda x: pd.Series(x.split('/')))

//anaconda/lib/python3.5/site-packages/pandas/core/generic.py:2701: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [31]:
bc['Breed'].columns = ['Breed','SecondarBreed']
bc['Breed'] = bc['Breed'].apply(lambda x: x.replace(' ', ''))

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [40]:
breed_counts = bc['Breed'].value_counts()
frequent_breeds = breed_counts[breed_counts>50].to_dict().keys()
bc.loc[~bc['Breed'].isin(frequent_breeds),'Breed'] = 'Rare'

//anaconda/lib/python3.5/site-packages/pandas/core/indexing.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [39]:

breeds = bc["Breed"].apply(lambda x: x.split(" Mix")[0])
breeds = breeds.apply(lambda x: re.sub('Black\s?|Tan\s?', '', x))
breeds = breeds.apply(lambda x: re.sub('^/', '', x))
breeds = breeds.str.replace("//", "")
breeds = breeds.apply(lambda x: pd.Series(x.split("/")))
breeds.columns = ['Breed', 'SecondaryBreed']
breed_counts = breeds["Breed"].value_counts()
frequent_breeds = breed_counts[breed_counts > 50].to_dict().keys()
breeds[~breeds['Breed'].isin(frequent_breeds)] = "Rare"

bc.drop('Breed', inplace=True, axis = 1)
bc = pd.concat([bc, breeds], axis = 1)
bc.drop('SecondaryBreed', inplace=True,axis = 1)

bc.loc[train.Breed.str.contains('Mix'),'Mix'] = 'Mix'
bc.loc[train.Breed.str.contains('/'),'Mix'] = 'Mix'

DomesticShorthair       8958
ChihuahuaShorthair      2145
PitBull                 2113
LabradorRetriever       1915
DomesticMediumHair       883
GermanShepherd           826
DomesticLonghair         547
AustralianCattleDog      511
Dachshund                510
Siamese                  426
Rare                     411
Boxer                    360
BorderCollie             334
MiniaturePoodle          310
AustralianShepherd       229
YorkshireTerrier         226
JackRussellTerrier       222
Beagle                   220
MiniatureSchnauzer       220
Catahoula                218
RatTerrier               215
SiberianHusky            194
Rottweiler               181
ShihTzu                  176
ChihuahuaLonghair        168
CairnTerrier             142
Pointer                  139
GreatPyrenees            131
AmericanBulldog          130
AnatolShepherd           118
                        ...
CollieRough               19
NorwichTerrier            18
BelgianMalinois           18
Greyhound                 18
Himalayan                 18
Basenji                   18
DogoArgentino             17
Vizsla                    17
Dalmatian                 17
StandardSchnauzer         17
AlaskanHusky              16
ItalianGreyhound          15
EnglishPointer            15
Persian                   14
AmericanEskimo            14
Bulldog                   14
ChesaBayRetr              13
PharaohHound              13
Pbgv                      13
Beauceron                 12
CavalierSpan              12
Ragdoll                   12
Newfoundland              12
St.BernardSmoothCoat      12
FrenchBulldog             11
Bullmastiff               11
Brittany                  11
AlaskanMalamute           11
Havanese                  11
FinnishSpitz              11
Name: Breed, dtype: int64

In [83]:
test = pd.read_csv('test.csv')
bc_t = pd.DataFrame()
bc_t = test[['Breed', 'Color']]
bc_t['Mix'] = 'Pure'
bc_t.loc[train.Breed.str.contains('Mix'),'Mix'] = 'Mix'
bc_t.loc[train.Breed.str.contains('/'),'Mix'] = 'Mix'

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
//anaconda/lib/python3.5/site-packages/pandas/core/indexing.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [86]:
breeds_t = bc_t["Breed"].apply(lambda x: x.split(" Mix")[0])
breeds_t = breeds_t.apply(lambda x: re.sub('Black\s?|Tan\s?', '', x))
breeds_t = breeds_t.apply(lambda x: re.sub('^/', '', x))
breeds_t = breeds_t.str.replace("//", "")
breeds_t = breeds_t.apply(lambda x: pd.Series(x.split("/")))

In [90]:
breeds_t.columns = ['Breed', 'SecondaryBreed']
breeds_t[~breeds_t['Breed'].isin(frequent_breeds)] = "Rare"

In [92]:
bc_t.drop('Breed', inplace=True, axis = 1)
bc_t = pd.concat([bc_t, breeds_t], axis = 1)
bc_t.drop('SecondaryBreed', inplace=True,axis = 1)

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [102]:
bc_t['Color'] = [x[0] for x in bc_t['Color'].str.split('/').tolist()]

In [103]:
bc_t.Breed = b_encoder.transform(bc_t.Breed)
bc_t.Color = c_encoder.transform(bc_t.Color)

In [105]:
bc_t.drop('Mix', axis = 1, inplace = True)

In [107]:
cleaned_test = pd.read_csv('cleaned_test.csv')
cleaned_test = pd.concat([cleaned_test,bc_t], axis = 1)

In [108]:
cleaned_test.drop(['ColorCode','BreedCode'],inplace = True, axis = 1)
cleaned_test.to_csv('clean_test_bc.csv', index = False)

In [109]:
cleaned_test

,AnimalType,AgeCode,IntactOrNot,NameCode,Hour,Weekday,Day of Month,Month,Year,Color,Breed
0,1,1,0.0,1,12,0,12,10,2015,40,32
1,1,1,1.0,1,17,5,26,7,2014,2,28
2,0,1,1.0,1,12,2,13,1,2016,18,27
3,1,1,0.0,1,18,5,28,12,2013,53,46
4,1,1,1.0,1,17,3,24,9,2015,54,37
5,1,1,1.0,1,11,1,23,6,2015,15,8
6,0,3,1.0,1,9,2,12,3,2014,18,26
7,0,1,1.0,1,8,2,25,6,2014,18,27
8,1,1,1.0,1,18,2,12,11,2014,2,14
9,1,1,1.0,1,17,0,7,4,2014,15,40
10,1,1,1.0,1,17,2,1,1,2014,54,32
11,1,1,0.0,1,15,4,19,9,2014,7,40
12,1,1,1.0,1,15,6,25,1,2015,16,40
13,1,1,1.0,0,18,1,22,9,2015,54,37
14,1,1,1.0,1,19,6,20,7,2014,2,46
15,1,1,1.0,1,18,2,26,3,2014,54,42
16,1,2,1.0,1,17,4,29,5,2015,2,24
17,1,1,1.0,1,19,1,19,1,2016,54,46
18,0,1,1.0,1,12,0,16,6,2014,50,27
19,0,2,0.0,0,19,1,11,2,2014,50,27
20,0,1,1.0,1,19,4,14,11,2014,2,27
21,0,1,NaN,0,13,0,4,5,2015,2,27
22,1,1,1.0,1,14,5,7,6,2014,54,46
23,0,1,0.0,0,15,6,20,7,2014,51,27
24,1,1,1.0,1,16,5,26,10,2013,49,39
25,0,1,1.0,0,13,0,29,12,2014,18,27
26,0,1,1.0,1,16,3,23,7,2015,4,26
27,1,1,0.0,0,8,3,19,3,2015,15,46
28,1,1,1.0,1,17,3,9,10,2014,2,32
29,1,1,1.0,1,17,1,13,5,2014,2,32
...,...,...,...,...,...,...,...,...,...,...,...
11426,1,2,1.0,1,14,5,28,12,2013,15,13
11427,1,1,0.0,1,15,5,21,12,2013,16,1
11428,1,1,1.0,1,12,4,15,11,2013,40,51
11429,1,1,1.0,1,18,0,17,2,2014,44,28
11430,0,1,1.0,0,12,0,8,12,2014,7,27
11431,0,1,0.0,0,9,1,30,6,2015,12,27
11432,1,2,1.0,1,17,4,21,3,2014,54,34
11433,0,1,0.0,1,16,6,16,8,2015,2,27
11434,1,2,1.0,1,12,6,6,9,2015,2,15
11435,0,1,0.0,0,17,3,13,8,2015,18,27
11436,0,1,1.0,0,17,4,21,3,2014,2,27
11437,1,1,0.0,1,13,4,10,1,2014,54,17
11438,1,1,1.0,0,20,5,2,5,2015,44,32
11439,1,1,1.0,1,16,6,18,5,2014,54,40
11440,0,1,NaN,0,17,1,20,10,2015,18,27
11441,1,2,1.0,1,17,2,7,1,2015,7,40
11442,1,1,1.0,1,16,5,28,11,2015,49,18
11443,0,1,1.0,1,12,5,4,10,2014,50,25
11444,0,1,0.0,0,17,6,1,6,2014,21,27
11445,0,1,0.0,0,14,1,14,4,2015,54,27
11446,0,1,1.0,0,20,6,19,7,2015,2,27
11447,1,1,1.0,1,12,6,19,10,2014,36,17
11448,1,1,1.0,0,17,6,17,8,2014,15,32
11449,1,1,1.0,1,14,0,20,7,2015,9,46
11450,1,1,1.0,1,17,3,5,11,2015,49,53
11451,0,1,1.0,0,14,1,8,7,2014,2,27
11452,0,1,0.0,0,12,1,21,10,2014,7,27
11453,0,1,0.0,0,9,0,29,9,2014,21,27
11454,1,2,1.0,1,17,5,5,9,2015,2,28
11455,1,2,0.0,1,18,5,12,7,2014,25,32