In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy
seed = 10
numpy.random.seed(seed)

Using Theano backend.

In [2]:
import pandas as pd
dataset = pd.read_csv('numerical_train.csv')
test = pd.read_csv('numerical_test.csv')

In [3]:
train_col =list(dataset.columns)
train_col.remove('outcome')
train_col.remove('people_id')

In [4]:
X = dataset[train_col]
Y = dataset['outcome']
X.shape

(2197291, 43)

In [5]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: outcome, dtype: int64

In [6]:
X = X.as_matrix()
Y = Y.as_matrix()

In [7]:
from keras.layers import advanced_activations
from keras.layers import Dropout
model = Sequential()
model.add(Dense(40, input_dim = 43,init ='uniform',activation = 'relu'))
model.add(Dropout(0.2))
#model.add(advanced_activations.LeakyReLU(alpha=0.1))
#model.add(Dense(30,init = 'uniform',activation = 'relu'))
#model.add(Dense(20,init = 'uniform',activation = 'relu'))
#model.add(Dense(10,init = 'uniform',activation = 'relu'))
#model.add(Dense(10,init = 'uniform',activation = 'relu'))
#model.add(Dense(10,init = 'uniform',activation = 'relu'))
#model.add(Dense(10,init = 'uniform',activation = 'relu'))
model.add(Dense(1,input_dim = 43, init = 'uniform', activation = 'sigmoid'))
model.compile(loss ='binary_crossentropy',optimizer = 'sgd',metrics = ['accuracy'])

In [8]:
model.fit(X,Y,nb_epoch = 50,batch_size = 100,verbose = 2, shuffle = False,validation_split = 0.1)

Train on 1977561 samples, validate on 219730 samples
Epoch 1/50
10s - loss: 7.0318 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 2/50
10s - loss: 7.0319 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 3/50
9s - loss: 7.0317 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 4/50
10s - loss: 7.0315 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 5/50
9s - loss: 7.0321 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 6/50
9s - loss: 7.0320 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 7/50
9s - loss: 7.0317 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 8/50
9s - loss: 7.0320 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 9/50
9s - loss: 7.0323 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 10/50
9s - loss: 7.0321 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 11/50
9s - loss: 7.0320 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 12/50
9s - loss: 7.0311 - acc: 0.5638 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 13/50
9s - loss: 7.0323 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 14/50
9s - loss: 7.0318 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 15/50
9s - loss: 7.0316 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 16/50
9s - loss: 7.0320 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 17/50
9s - loss: 7.0317 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 18/50
9s - loss: 7.0315 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 19/50
9s - loss: 7.0323 - acc: 0.5637 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 20/50
9s - loss: 7.0311 - acc: 0.5638 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 21/50
9s - loss: 7.0294 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 22/50
10s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 23/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 24/50
11s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 25/50
13s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 26/50
13s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 27/50
12s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 28/50
11s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 29/50
12s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 30/50
11s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 31/50
11s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 32/50
13s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 33/50
11s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 34/50
12s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 35/50
10s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 36/50
11s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 37/50
10s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 38/50
10s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 39/50
11s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 40/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 41/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 42/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 43/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 44/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 45/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 46/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 47/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 48/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 49/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855
Epoch 50/50
9s - loss: 7.0293 - acc: 0.5639 - val_loss: 8.2930 - val_acc: 0.4855

2196480/2197291 [============================>.] - ETA: 0s

In [9]:
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

NameError: name 'scores' is not defined

In [33]:
model.fit(X,Y,nb_epoch = 150,batch_size = 100,verbose = 2, shuffle = True)

Epoch 1/150
23s - loss: 0.6871 - acc: 0.5561
Epoch 2/150
25s - loss: 0.6869 - acc: 0.5560
Epoch 3/150
27s - loss: 0.6869 - acc: 0.5560
Epoch 4/150

KeyboardInterrupt:

In [35]:
del test['people_id']
test

,activity_id,activity_category,char_1,group_1,char_2,char_3,char_4,char_5,char_6,char_7,...,char_31,char_32,char_33,char_34,char_35,char_36,char_37,char_38,weekday_x,weekday_y
0,249281,1,2,22593,3,40,25,9,4,16,...,1,1,1,1,1,1,1,76,3,3
1,230855,5,2,22593,3,40,25,9,4,16,...,1,1,1,1,1,1,1,76,3,3
2,240724,1,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,5,5
3,83552,1,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
4,1043301,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
5,112890,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
6,1169930,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
7,1924448,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
8,1953554,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
9,1971739,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,1,5
10,2839282,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
11,2889351,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
12,3238933,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
13,3384798,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
14,3701358,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
15,3715695,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
16,3734085,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
17,3961391,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
18,4167474,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
19,4397847,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
20,4649285,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
21,538607,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
22,584216,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
23,596561,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,6,5
24,649143,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
25,659237,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,7,5
26,688604,5,2,25417,3,6,6,4,1,1,...,1,1,1,1,1,1,1,90,1,5
27,218751,1,2,17304,2,8,7,8,1,7,...,0,0,0,0,0,0,0,2,4,4
28,383524,1,2,17304,2,8,7,8,1,7,...,0,0,0,0,0,0,0,2,4,4
29,3973689,3,2,17304,2,8,7,8,1,7,...,0,0,0,0,0,0,0,2,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498657,3146168,5,2,667,3,40,25,9,1,2,...,0,1,0,1,0,1,1,98,4,7
498658,3435600,5,2,667,3,40,25,9,1,2,...,0,1,0,1,0,1,1,98,6,7
498659,3648161,5,2,667,3,40,25,9,1,2,...,0,1,0,1,0,1,1,98,4,7
498660,4609368,5,2,667,3,40,25,9,1,2,...,0,1,0,1,0,1,1,98,5,7
498661,488594,5,2,667,3,40,25,9,1,2,...,0,1,0,1,0,1,1,98,4,7
498662,568974,3,2,667,3,40,25,9,1,2,...,0,1,0,1,0,1,1,98,7,7
498663,187412,1,2,11303,3,40,25,9,1,23,...,1,1,1,1,1,1,1,95,3,3
498664,1907199,3,2,11303,3,40,25,9,1,23,...,1,1,1,1,1,1,1,95,4,3
498665,3825329,7,2,11303,3,40,25,9,1,23,...,1,1,1,1,1,1,1,95,4,3
498666,4540493,2,2,11303,3,40,25,9,1,23,...,1,1,1,1,1,1,1,95,4,3
498667,4716058,4,2,11303,3,40,25,9,1,23,...,1,1,1,1,1,1,1,95,4,3
498668,1374659,2,2,17304,2,4,6,4,3,8,...,0,0,0,0,0,0,0,0,4,6
498669,4191036,4,2,17304,2,4,6,4,3,8,...,0,0,0,0,0,0,0,0,4,6
498670,1893941,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,2,6
498671,2245699,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,2,6
498672,2316472,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,4,6
498673,2372813,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,6,6
498674,2433185,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,6,6
498675,2576346,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,2,6
498676,2718841,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,5,6
498677,2902742,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,2,6
498678,3448131,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,4,6
498679,3757705,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,2,6
498680,4149173,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,6,6
498681,4355610,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,6,6
498682,4367092,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,6,6
498683,4404220,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,6,6
498684,448830,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,2,6
498685,450133,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,2,6
498686,847967,2,2,17304,2,40,25,9,3,8,...,0,0,0,0,0,0,0,36,6,6

In [38]:
test = test.as_matrix()

In [57]:
proba = model.predict_proba(test, batch_size=100, verbose=2)
proba[0:100]

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32)

In [10]:
from keras.utils.visualize_util import plot
plot(model, to_file='model.png')

ImportError: No module named 'pydot'