In [77]:
import pandas as pd
import numpy as np

In [78]:
act_train = pd.read_csv('act_train.csv')
act_test = pd.read_csv('act_test.csv')
people = pd.read_csv('people.csv')
sub_id = act_test['activity_id']

In [79]:
act_train.columns

Index(['people_id', 'activity_id', 'date', 'activity_category', 'char_1',
       'char_2', 'char_3', 'char_4', 'char_5', 'char_6', 'char_7', 'char_8',
       'char_9', 'char_10', 'outcome'],
      dtype='object')

In [80]:
train = pd.merge(act_train,people, how = 'left',on ='people_id',left_index = True)
test = pd.merge(act_test,people, how = 'left',on ='people_id',left_index = True)

In [81]:
train_col = train.columns.tolist()

In [82]:
train_col.remove('outcome')

In [83]:
train_col

['people_id',
 'activity_id',
 'date_x',
 'activity_category',
 'char_1_x',
 'char_2_x',
 'char_3_x',
 'char_4_x',
 'char_5_x',
 'char_6_x',
 'char_7_x',
 'char_8_x',
 'char_9_x',
 'char_10_x',
 'char_1_y',
 'group_1',
 'char_2_y',
 'date_y',
 'char_3_y',
 'char_4_y',
 'char_5_y',
 'char_6_y',
 'char_7_y',
 'char_8_y',
 'char_9_y',
 'char_10_y',
 'char_11',
 'char_12',
 'char_13',
 'char_14',
 'char_15',
 'char_16',
 'char_17',
 'char_18',
 'char_19',
 'char_20',
 'char_21',
 'char_22',
 'char_23',
 'char_24',
 'char_25',
 'char_26',
 'char_27',
 'char_28',
 'char_29',
 'char_30',
 'char_31',
 'char_32',
 'char_33',
 'char_34',
 'char_35',
 'char_36',
 'char_37',
 'char_38']

In [107]:
train[train_col]

,people_id,activity_id,date_x,activity_category,char_1_x,char_2_x,char_3_x,char_4_x,char_5_x,char_6_x,...,char_29,char_30,char_31,char_32,char_33,char_34,char_35,char_36,char_37,char_38
0,ppl_100,act2_1734928,2023-08-26,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,True,False,False,True,True,True,False,36
0,ppl_100,act2_2434093,2022-09-27,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,True,False,False,True,True,True,False,36
0,ppl_100,act2_3404049,2022-09-27,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,True,False,False,True,True,True,False,36
0,ppl_100,act2_3651215,2023-08-04,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,True,False,False,True,True,True,False,36
0,ppl_100,act2_4109017,2023-08-26,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,True,False,False,True,True,True,False,36
0,ppl_100,act2_898576,2023-08-04,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,True,False,False,True,True,True,False,36
1,ppl_100002,act2_1233489,2022-11-23,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,True,True,True,True,True,True,False,76
1,ppl_100002,act2_1623405,2022-11-23,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,True,True,True,True,True,True,False,76
2,ppl_100003,act2_1111598,2023-02-07,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_1177453,2023-06-28,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_133509,2022-08-10,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_1408475,2023-03-02,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_1610829,2022-09-13,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_1688731,2023-02-10,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_1961720,2023-06-28,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_1988351,2022-08-23,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_2198176,2022-08-16,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_2437661,2023-02-02,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_2476911,2023-03-02,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_2557270,2022-08-30,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_2581989,2023-02-21,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_3116385,2023-02-15,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_3159712,2022-08-30,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_3292005,2023-05-03,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_3461867,2023-08-02,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_3468306,2023-03-02,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_3867292,2023-02-10,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_3990676,2023-08-30,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_4102292,2023-08-30,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
2,ppl_100003,act2_4160587,2023-02-21,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,True,True,True,True,False,True,True,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189116,ppl_99994,act2_2053669,2023-01-19,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2053762,2023-06-16,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2134893,2023-08-23,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2139237,2023-06-27,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2233766,2023-06-28,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2499779,2023-02-19,type 3,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2514377,2023-06-15,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2537795,2023-01-12,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2582736,2023-06-16,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2674371,2023-06-16,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2808953,2023-05-02,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2840212,2023-08-25,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_2992386,2023-06-15,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_3177773,2023-06-15,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_3284072,2023-07-14,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_3373847,2023-02-16,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_3534467,2023-08-17,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_3903321,2023-06-16,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_4024188,2023-01-12,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_4355021,2023-02-23,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_4433480,2023-01-24,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_4440524,2023-08-17,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_4473896,2023-06-15,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_4479985,2023-07-14,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_4581579,2023-01-13,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_4668076,2023-06-16,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_4743548,2023-03-30,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_536973,2023-01-19,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_688656,2023-05-02,type 4,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95
189116,ppl_99994,act2_715089,2023-06-15,type 2,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,True,True,False,True,True,True,True,95

In [84]:
from sklearn.feature_extraction import FeatureHasher
h = FeatureHasher(input_type = 'string')
data = h.fit_transform(train[train_col])

In [103]:
train['outcome'] = train['outcome'].astype('str')
target = h.transform(train['outcome'])

In [86]:
#np.set_printoptions(threshold=np.inf)
test = h.transform(test)

In [105]:
data.shape

(54, 1048576)

In [91]:
from keras.models import Sequential
from keras.layers import Dense
seed = 7
np.random.seed(seed)

In [98]:
from keras.layers import advanced_activations
model = Sequential()
model.add(Dense(50,input_dim =1048576,init ='uniform',activation = 'relu' ))
model.add(advanced_activations.LeakyReLU(alpha=0.1))
#model.add(Dense(30,init = 'uniform',activation = 'relu'))
#model.add(Dense(20,init = 'uniform',activation = 'relu'))
#model.add(Dense(10,init = 'uniform',activation = 'relu'))
#model.add(Dense(10,init = 'uniform',activation = 'relu'))
#model.add(Dense(10,init = 'uniform',activation = 'relu'))
#model.add(Dense(10,init = 'uniform',activation = 'relu'))
model.add(Dense(1, init = 'uniform', activation = 'sigmoid'))
model.compile(loss ='binary_crossentropy',optimizer = 'sgd',metrics = ['accuracy'])

In [106]:
model.fit(data,target,nb_epoch = 5,batch_size = 100,verbose = 2, shuffle = False,validation_split = 0.1)

Exception: Error when checking model target: expected dense_3 to have shape (None, 1) but got array with shape (2197291, 1048576)